### ISSUE TITLE
TextDrawable is not being loaded

### ISSUE THREAD

**Issue by pmrzygweb** [GetStream/avatarview-android#18]
I am using this library for name initials placeholder - https://github.com/amulyakhare/TextDrawable
However, AvatarView doesn't load TextDrawable somehow
Any help is appreciated

**Comment by skydoves** [comment]
Hi @pmrzygweb,
Thank you for reporting this issue. Unfortunately, the `TextDrawable` you suggested is not supported by Coil and Glide. AvatarView uses Coil and Glide to load network or local images. I would like to suggest just you should implement by overlapping the AvatarView in your layout.

**Comment by pmrzygweb** [comment]
@skydoves Thanks for your reply.
The problem is that I can overlay it for single icon but no way for group icons (more than 2 users)

**Comment by pmrzygweb** [comment]
@skydoves Do you have any suggestion?

**Comment by skydoves** [comment]
Hi @pmrzygweb, 
You can use the `TextDrawable` because Coil does not support it.

There is one way but it's a bit complicated.

1. Build a [custom AvatarBitmapFactory](https://github.com/getStream/avatarview-android#custom-avatarbitmapfactory).  You can just copy the [StreamAvatarBitmapFactory](https://github.com/GetStream/avatarview-android/blob/main/avatarview-stream-integration/src/main/kotlin/io/getstream/avatarview/stream/integration/StreamAvatarBitmapFactory.kt) with some modifications.
2. As you can reference [here](https://github.com/GetStream/avatarview-android/blob/main/avatarview-stream-integration/src/main/kotlin/io/getstream/avatarview/stream/integration/AvatarViewStreamIntegration.kt#L78), you can load the image by passing `Avatar` to the `loadImage`.
3. [Put the initials relevant data as the extra data](https://github.com/GetStream/avatarview-android/blob/main/avatarview-stream-integration/src/main/kotlin/io/getstream/avatarview/stream/integration/AvatarViewStreamIntegration.kt#L105) according to the URLs. So you can take out the extra data from the custom `AvatarBitmapFactory` and it will draw your initials with the extra data.

You can finally implement the result below:

![image](https://user-images.githubusercontent.com/24237865/157881136-269b8b9e-430c-4b49-a998-f2c6f9d1ed12.png)

This is quite a complicated way, but this is the only way to accomplish it for now.

**Comment by skydoves** [comment]
I'll review this if we can support it as an independent artifact in the future!
