### ISSUE TITLE
Drawable positioning issue in avatarview-coil when configuration changes happen

### ISSUE THREAD

**Issue by BreathingCapybara** [GetStream/avatarview-android#23]
갤럭시 액티브3에 샘플코드를 그대로 다운받고 기기를 회전시켜봤습니다.

![PXL_20220509_233536320.jpg](https://user-images.githubusercontent.com/8628247/167515173-1d5bf58d-db40-4dd3-a837-f4d0f64a9c40.jpg)

**Comment by skydoves** [comment]
Hi, @BreathingCapybara 
thank you for reporting this issue. This issue came from the Coil version `1.x.x`, which has a positioning issue when configuration changes happen. I just checked out the issue has been fixed in the `2.x.x` version, but it's currently not stable so I will keep eye on the updates and I will let you know when it's ready to release. Thanks!

**Comment by skydoves** [comment]
This issue has been fixed at the head of the main branch. Thank you for reporting this issue!
